#!/usr/bin/env bash
# Installs nginx and configures it to listen on port 80.  Returns "301 moved permanantly" from get requests
sudo sed -i "29i\\\t add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
