#!/usr/bin/env bash
# installs latest haproxy and configures it to split between two servers
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt -y update
sudo apt -y install haproxy
echo '
frontend localnodes
	bind *:80
	mode http
	default_backend nodes

backend nodes
	mode http
	balance roundrobin
	server 264-web-01 107.22.148.78:80 check
	server 264-web-02 54.204.244.213:80 check' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
