#!/usr/bin/env bash
#Ping the provided host 5 times.  Provides instructions on improper use.
if [ $# -lt 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$@"
    ((count++))
fi
