#!/usr/bin/env bash
#display numbers 1-100. on multiples of 3 print Fizz, 5 print Buzz, 15 print FizzBuzz
count=1
while [ $count -le 100 ]; do
    if ((count % 15 == 0)); then
        echo "FizzBuzz"
    elif ((count % 5 == 0)); then
        echo "Buzz"
    elif ((count % 3 == 0)); then
        echo "Fizz"
    else
        echo "$count"
    fi
    ((count++))
done
