#!/usr/bin/env bash
#display bad luck on 4th iteration, good luck on 8th iteration Holberton School otherwise
count=1
while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    let count+=1
done
