#!/usr/bin/env bash
#display bad luck from <country> on 4th 9th and 17th iteration otherwise print number
count=1
while [ $count -le 20 ]; do
    if [ $count -eq 4 ]; then
        echo "bad luck from China"
    elif [ $count -eq 9 ]; then
        echo "bad luck from Japan"
    elif [ $count -eq 17 ]; then
        echo "bad luck from Italy"
    else
        echo "$count"
    fi
    ((count++))
done
