#!/usr/bin/env bash
#display bad luck from <country> on 4th 9th and 17th iteration otherwise print number
count=1
while [ $count -le 20 ]; do
    case $count in
        4) echo "bad luck from China" ;;
        9) echo "bad luck from Japan" ;;
        17) echo "bad luck from Italy" ;;
        *) echo "$count" ;;
    esac
    ((count++))
done
